name: CI

on:
  pull_request:
  workflow_call:

jobs:
  ci:
    name: CI Passed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: CI Passed
        run: |
          echo "✅ CI passed"