name: Publish Nos Cli

on:
  workflow_dispatch:
    inputs:
      app:
        description: "Publish app"
        required: true
        default: "cli"
        type: choice
        options:
          - cli
          - web

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Publish
        run: |
          echo "publish ${{ inputs.app }}"